- name: Install wget
  apt: pkg=wget
  become: yes

- name: Get lein
  get_url: url=https://raw.github.com/technomancy/leiningen/stable/bin/lein dest=/usr/local/bin/lein mode=0755
  become: yes

- name: Install lein
  command: lein --version
